### ISSUE TITLE
Failed to launch QuickLook error

### ISSUE THREAD

**Issue by heldheld** [Flow-Launcher/Flow.Launcher.Plugin.QuickLook#2]
Have yet to be able to successfully use QuickLook. Always get this error whenever searching with the Preview window open:
![image](https://github.com/user-attachments/assets/444e09ba-d27a-4fbc-b2ad-afa0336aff27)

I'm running the portable version, maybe that plays a role? Although I would expect this to work with the portable version.

**Comment by heldheld** [comment]
Ah, it was not specified that you'd have to have QuickLook installed and running on Windows, besides the plugin, but it appears that is a requirement. It works now.

**Comment by EnigmaSolved** [comment]
> Ah, it was not specified that you'd have to have QuickLook installed and running on Windows, besides the plugin, but it appears that is a requirement. It works now.

Hey, @heldheld, where did you download QuickLook from? I see multiple versions out there (eg, WinQuickLook, Seer, etc.), by different creators -- I'm not clear on which one is the correct one to use with this plugin....

**Comment by jjw24** [comment]
Hey there, this is the QuickLook for use by the plugin https://github.com/QL-Win/QuickLook.

**Comment by EnigmaSolved** [comment]
> Hey there, this is the QuickLook for use by the plugin https://github.com/QL-Win/QuickLook.

Thank you so much, @jjw24! :)

**Comment by heldheld** [comment]
> Hey, @heldheld, where did you download QuickLook from? I see multiple versions out there (eg, WinQuickLook, Seer, etc.), by different creators -- I'm not clear on which one is the correct one to use with this plugin....

I got it from the Microsoft Store, I think it's the same one as jjw24 linked(?). Anyway, you're already up and running I reckon, enjoy 😉.
